showNavigation: false
logLevel: "INFO"
showNewVersions: false
showFooter: false

actions:
  - title: "Start Navigation Stack"
    shell: podman-compose -f /repo/docker-compose.yaml up -d navigation
    icon: '<img src = "customIcons/nav2_start.png" width = "48px"/>'
  - title: "Stop Navigation Stack"
    shell: docker compose -f /repo/docker-compose.yaml down navigation
    icon: '<img src = "customIcons/nav2_stop.png" width = "48px"/>'
  - title: "Start Mapping"
    shell: docker compose -f /repo/docker-compose.yaml up -d mapping
    icon: '<img src = "customIcons/mapping_start.gif" width = "48px"/>'
  - title: "Stop Mapping"
    shell: docker compose -f /repo/docker-compose.yaml down mapping
    icon: '<img src = "customIcons/mapping_stop.gif" width = "48px"/>'
  - title: "Restart Teleop"
    icon: '<img src = "customIcons/gamepad.png" width = "48px"/>'
    shell: docker restart cps_loki-teleop-1
  - title: Restart or Shutdown System
    icon: restart
    shell: systemctl {{ choice }}
    arguments:
      - name: choice
        title: Pick one
        choices:
          - value: reboot
          - value: shutdown
          - value: grafana
  # This will SSH into a server an run the command 'service httpd restart'
  - title: Restart httpd on Server 1
    shell: ssh bjorn@loki.local 'echo "it works"'
    icon: ping
    timeout: 5